// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7Q09CSHmp8JGNpwpsoFllAnj5swXNvM',
    appId: '1:925886768678:web:29c5731c48103c868868e7',
    messagingSenderId: '925886768678',
    projectId: 'bugdex-74d33',
    authDomain: 'bugdex-74d33.firebaseapp.com',
    storageBucket: 'bugdex-74d33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJ4E_fb7F4sZ1R1VlpPxiQCnzGdrAi8s',
    appId: '1:925886768678:android:4ba2db9b9490592d8868e7',
    messagingSenderId: '925886768678',
    projectId: 'bugdex-74d33',
    storageBucket: 'bugdex-74d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rqonskSo_EnLS3AvLMEQ_2jl2zaC41I',
    appId: '1:925886768678:ios:066fefb5856c78a28868e7',
    messagingSenderId: '925886768678',
    projectId: 'bugdex-74d33',
    storageBucket: 'bugdex-74d33.appspot.com',
    iosBundleId: 'com.example.bugdex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-rqonskSo_EnLS3AvLMEQ_2jl2zaC41I',
    appId: '1:925886768678:ios:56e3ba365c32c6708868e7',
    messagingSenderId: '925886768678',
    projectId: 'bugdex-74d33',
    storageBucket: 'bugdex-74d33.appspot.com',
    iosBundleId: 'com.example.bugdex.RunnerTests',
  );
}
